DROP TABLE IF EXISTS DEPARTMENT
GO

 

CREATE TABLE DEPARTMENT
(
DEPARTMENT_ID INT,
DEPARTEMENT_NAME VARCHAR(100)
)

INSERT INTO DEPARTMENT VALUES(1, 'Computer Departement')
INSERT INTO DEPARTMENT VALUES(2, 'IT Departement')
INSERT INTO DEPARTMENT VALUES(3, 'Civil Departement')
INSERT INTO DEPARTMENT VALUES(4, 'Mechanical Departement')
INSERT INTO DEPARTMENT VALUES(5, 'Electrical Departement')


DROP TABLE IF EXISTS STUDENT_INFORMATION
GO
CREATE TABLE STUDENT_INFORMATION
(
STUDENT_ID INT,
FIRST_NAME VARCHAR(100),
LAST_NAME VARCHAR(100),
CITY VARCHAR(100),
DEPARTMENT_ID INT
)

-- COMPUTER DEPARTEMENT STUDENT

INSERT INTO STUDENT_INFORMATION VALUES(1,'Rushikesh','Pandit','Sangamner',1)
INSERT INTO STUDENT_INFORMATION VALUES(2,'Shriram','Aghav','Newasa',1)
INSERT INTO STUDENT_INFORMATION VALUES(3,'Bhushan','Patil','Akole',1)

-- IT DEPARTEMENT STUDENT
INSERT INTO STUDENT_INFORMATION VALUES(4,'Priti','Hase','Sangamner',2)
INSERT INTO STUDENT_INFORMATION VALUES(5,'Apurva','Shindhe','Newasa',2)
INSERT INTO STUDENT_INFORMATION VALUES(6,'Monali','Kole','Akole',2)

-- CIVIL DEPARTEMENT STUDENT
INSERT INTO STUDENT_INFORMATION VALUES(7,'Saurabh','Rashinkar','Mumbai',3)
INSERT INTO STUDENT_INFORMATION VALUES(8,'Akash','Kakan','Bramati',3)
INSERT INTO STUDENT_INFORMATION VALUES(9,'Mahesh','Raut','Pune',3)

-- MECHANICAL DEPARTEMENT STUDENT
INSERT INTO STUDENT_INFORMATION VALUES(10,'Prashant','Kumar','Ranchi',4)
INSERT INTO STUDENT_INFORMATION VALUES(11,'Aditya','Kale','Newasa',4)
INSERT INTO STUDENT_INFORMATION VALUES(12,'Kabir','Saraf','Nanded',4)

-- DEPARTMENT NOTEXISTS 
INSERT INTO STUDENT_INFORMATION VALUES(13,'XYZ','XYZ','Newasa',5)
INSERT INTO STUDENT_INFORMATION VALUES(14,'PQR','PQR','Nanded',5)
DROP TABLE IF EXISTS STUDENT_ACADAMIC_DATA
GO

CREATE TABLE STUDENT_ACADAMIC_DATA(
STUDNET_ID INT,
FE_CGPA DECIMAL(18,2),
SE_CGPA DECIMAL(18,2),
TE_CGPA DECIMAL(18,2),
BE_CGPA DECIMAL(18,2)

)



INSERT INTO STUDENT_ACADAMIC_DATA VALUES(1,9.2,8.9,9.4,8.7)
INSERT INTO STUDENT_ACADAMIC_DATA VALUES(2,7.2,9.9,6.4,9.4)
INSERT INTO STUDENT_ACADAMIC_DATA VALUES(3,8.2,7.9,7.4,7.7)

INSERT INTO STUDENT_ACADAMIC_DATA VALUES(4,8.2,6.9,9.3,8.7)
INSERT INTO STUDENT_ACADAMIC_DATA VALUES(5,6.2,5.9,6.9,6.4)
INSERT INTO STUDENT_ACADAMIC_DATA VALUES(6,9.2,5.9,7.6,9.7)



INSERT INTO STUDENT_ACADAMIC_DATA VALUES(7,8.2,6.9,9.3,8.7)
INSERT INTO STUDENT_ACADAMIC_DATA VALUES(8,6.2,5.9,6.9,6.4)
INSERT INTO STUDENT_ACADAMIC_DATA VALUES(9,9.2,5.9,7.6,9.7)



INSERT INTO STUDENT_ACADAMIC_DATA VALUES(12,8.2,6.9,9.3,8.7)
INSERT INTO STUDENT_ACADAMIC_DATA VALUES(11,6.2,5.9,6.9,6.4)
INSERT INTO STUDENT_ACADAMIC_DATA VALUES(10,9.2,5.9,7.6,9.7)
--SELECT * FROM STUDENT_ACADAMIC_DATA



SELECT * FROM STUDENT_INFORMATION SI WHERE SI.DEPARTMENT_ID=1
SELECT SI.FIRST_NAME, SI.LAST_NAME,D.DEPARTEMENT_NAME FROM STUDENT_INFORMATION SI INNER JOIN DEPARTMENT D ON SI.DEPARTMENT_ID=D.DEPARTMENT_ID
CREATE TABLE STUDENT_HOSTEL_DATA(
HOSTELID INT,HOSTELNAME VARCHAR(90),HOSTELRECTORNAME VARCHAR(90)

)
--SELECT * FROM STUDENT_HOSTEL_DATA SH INNER JOIN 



