-- sub query 
-- query inside query 



SELECT * FROM EMPLOYEE

-- QUE: FIND MAXIMUM SALARY FROM EMPLOYEE TABLE 

SELECT MAX(SALARY) FROM EMPLOYEE

-- QUE: FIND EMPLOYEE NAME WHO IS TAKING MAXIMUM SALARY FROM EMPLOYEE TABLE 

SELECT  MAX(SALARY) FROM EMPLOYEE E

-- QUE: WRITE A QUERY TO FIND EMPLOYEE WHOSE SALARY IS MAXIMUM SALARY 
-- QUE: WRITE A QUERY TO FIND EMPLOYEE WHOSE SALARY IS 750000

SELECT * FROM EMPLOYEE E WHERE E.SALARY=(SELECT  MAX(SALARY) FROM EMPLOYEE E)
SELECT * FROM EMPLOYEE E WHERE E.SALARY=(SELECT  MAX(SALARY) FROM EMPLOYEE E)

-- QUE: WRITE A QUERY TO FIND  SECOND MAX SALARY
-- QUE WRITE A QUERY TO PRINT 700000

--  WE HAVE TO PRINT MAXIMUM SALARY AMONG ALL SALARY BUT IT SHOULD NOT BE MAXIMUM 


SELECT  MAX(SALARY) FROM EMPLOYEE E
-- FIND MAXIMUM SALARY FROM EMPLOYEEE BUT IT SHOULD NOT BE 750000

-- FIND  RECORD FROM EMPLOYEEE BUT IT SHOULD NOT BE 750000

SELECT * FROM EMPLOYEE E WHERE E.SALARY != (75000.00)

SELECT * FROM EMPLOYEE E WHERE E.SALARY != (SELECT  MAX(SALARY) FROM EMPLOYEE E)

SELECT MAX(E.SALARY) FROM EMPLOYEE E WHERE E.SALARY != (SELECT  MAX(SALARY) FROM EMPLOYEE E2)
-- 2ND MAX SALRY -> 1 SUBQUERY
-- 3RD MAX  -> SUBQUERY 2
--4TH -> SUBQUERY 
--3000 TH -> SUBQUERY 2999 


-- WRITE A QUERY TO FIND EMPLOYEE HAVING SECOND MAXIMUM SALARY
-- WRITE A QUERY TO FIND EMPLOYEE WHOSE SALRY IS 700000

SELECT * FROM EMPLOYEE E WHERE E.SALARY=(SELECT MAX(E.SALARY) FROM EMPLOYEE E WHERE E.SALARY != (SELECT  MAX(SALARY) FROM EMPLOYEE E2))

SELECT * FROM EMPLOYEE E WHERE E.SALARY!=

SELECT MAX(E.SALARY) FROM EMPLOYEE E WHERE E.SALARY != (SELECT  MAX(SALARY) FROM EMPLOYEE E2)






-- QUERY TO FIND NTH MAXIMUM SALARY

-- N=3
SELECT * FROM EMPLOYEE E

-- FOR EACH RECORD IN TABLE CHECK HOW MANY SALARY ARE GREATER THAN CURRENT RECORD SALARY
-- RECORD COUNT WHOSE SALARY IS GREATER THAN CURRENT RECORD SALARY N-1
SELECT * FROM EMPLOYEE E WHERE E.EMPLOYEE_ID =3

-- 3RD MAX 
CURRENT RECORD SALARY  <GEATER SALARY RECORD -> COUNT = N-1
500000 -> 4
60000.00-> 3
500000 -> 4
70000.00-> 1
65000.00 ->  2

-- NTH MAX -> RECORD WHO IS HAVNIG N-1 SALARY GREATER THAN IT 

SELECT * FROM EMPLOYEE E WHERE 2= (SELECT COUNT(E2.SALARY) FROM  EMPLOYEE E2 WHERE E2.SALARY > E.SALARY) / 










