SELECT * FROM STUDENT_INFORMATION

--										***************** Stored procedure *******************************
--	An SQL stored procedure is a group of pre-compiled SQL statements (prepared SQL code) that can be reused by simply calling it whenever needed.
--	Stored procedures are very useful because they allow you to encapsulate (bundle) a set of SQL statements as a single unit and execute them
--	repeatedly with different parameters, making it easy to manage and reuse the code.


--Key points 
-- Resuable code
-- encapsulate (bundle) a set of SQL statements as a single unit and execute them
--manage easy 


SELECT * FROM STUDENT_INFORMATION SI WHERE SI.STUDENT_ID=1

SELECT * FROM STUDENT_INFORMATION SI WHERE SI.STUDENT_ID=2

SELECT * FROM STUDENT_INFORMATION SI WHERE SI.STUDENT_ID=3

SELECT * FROM STUDENT_INFORMATION SI WHERE SI.STUDENT_ID=4


int GET_STUDENT_INFO(int a , int b)
{
-- logical code 
}

GET_STUDENT_INFO(2,4)

-- CREATE 
DROP PROCEDURE IF EXISTS GET_STUDENT_INFO
GO
CREATE PROCEDURE GET_STUDENT_INFO
@STUDENT_ID int 
AS 
BEGIN
SELECT * FROM STUDENT_INFORMATION SI WHERE SI.STUDENT_ID=@STUDENT_ID
END

-- CALL 

EXECUTE GET_STUDENT_INFO @STUDENT_ID=9


SELECT * FROM STUDENT_INFORMATION
SELECT * FROM STUDENT_SPORT_INFORMATION
SELECT * FROM STUDENT_ACADAMIC_INFO
SELECT * FROM STUDENT_SPORT_INFORMATION
SELECT * FROM DEPARTMENT


SELECT SI.FIRST_NAME, SI.LAST_NAME, SAI.FE_CGPA, SAI.SE_CGPA, SAI.TE_CGPA, SAI.BE_CGPA FROM STUDENT_INFORMATION SI
INNER JOIN STUDENT_ACADAMIC_INFO SAI
ON SI.STUDENT_ID=SAI.STUDNET_ID
WHERE SI.STUDENT_ID=8


CREATE PROCEDURE GET_STUDENT_ACADAMIC_INFO
@STUDENT_ID INT
AS 
BEGIN 
SELECT SI.FIRST_NAME, SI.LAST_NAME, SAI.FE_CGPA, SAI.SE_CGPA, SAI.TE_CGPA, SAI.BE_CGPA FROM STUDENT_INFORMATION SI
INNER JOIN STUDENT_ACADAMIC_INFO SAI
ON SI.STUDENT_ID=SAI.STUDNET_ID
WHERE SI.STUDENT_ID=@STUDENT_ID
END

EXECUTE GET_STUDENT_ACADAMIC_INFO @STUDENT_ID=5


--QUE: STUDNET HAVING DEPARTMETN ID 1 AND ALL CGPA GRETER THATN 8

DROP PROCEDURE IF EXISTS GET_STUDNET_ACADAMIC_INFO_FOR_DEPARTMENT
GO
CREATE PROCEDURE GET_STUDNET_ACADAMIC_INFO_FOR_DEPARTMENT
@DEPARTMENT_ID INT
, @PRAMETER_NEW INT 
AS 
BEGIN
SELECT * FROM STUDENT_INFORMATION SI
INNER JOIN STUDENT_ACADAMIC_INFO SAI
ON SI.STUDENT_ID=SAI.STUDNET_ID
WHERE SI.DEPARTMENT_ID=@DEPARTMENT_ID AND SAI.FE_CGPA>7 AND SAI.SE_CGPA>7 AND SAI.TE_CGPA>7 AND SAI.BE_CGPA>7 AND SAI.BE_CGPA>@PRAMETER_NEW
END



SELECT * FROM STUDENT_INFORMATION
SELECT * FROM STUDENT_SPORT_INFORMATION

DROP PROCEDURE IF EXISTS STUDENT_COUNT
GO
CREATE PROCEDURE STUDENT_COUNT
@DEPARTMENT_NAME VARCHAR(100)
AS 
BEGIN
DECLARE @ORIGINAL_DEPT_ID INT;
SELECT @ORIGINAL_DEPT_ID=D.DEPARTMENT_ID FROM DEPARTMENT D WHERE  D.DEPARTEMENT_NAME=@DEPARTMENT_NAME
SELECT COUNT(*) FROM STUDENT_INFORMATION SI WHERE SI.DEPARTMENT_ID=@ORIGINAL_DEPT_ID;
END

EXECUTE STUDENT_COUNT @DEPARTMENT_NAME='IT Departement'


-- INPUT : SPORT NAME 
-- OUTPUT : STUDNET FIRST NAME, LAST NAME, SPORT 


CREATE PROCEDURE STUDNET_INFO_ABOUT_SPORT
@SPORT_NAME VARCHAR(100)
AS 
BEGIN
SELECT * FROM STUDENT_INFORMATION SI 
INNER JOIN STUDENT_SPORT_INFORMATION SSI ON SI.STUDENT_ID= SSI.STUDENT_ID
WHERE SSI.SPORT_NAME=@SPORT_NAME
END

EXECUTE STUDNET_INFO_ABOUT_SPORT @SPORT_NAME='Cricket'


DROP PROCEDURE IF EXISTS STUDENT_COUNT
GO
CREATE PROCEDURE STUDENT_COUNT
@DEPARTMENT_NAME VARCHAR(100)
AS 
BEGIN
DECLARE @ORIGINAL_DEPT_ID INT;
SELECT @ORIGINAL_DEPT_ID=D.DEPARTMENT_ID FROM DEPARTMENT D WHERE  D.DEPARTEMENT_NAME=@DEPARTMENT_NAME
SELECT COUNT(*) FROM STUDENT_INFORMATION SI WHERE SI.DEPARTMENT_ID=@ORIGINAL_DEPT_ID;
END


SELECT * FROM STUDENT_INFORMATION
SELECT * FROM STUDENT_SPORT_INFORMATION
SELECT *FROM DEPARTMENT
--QUE 2: INPUT DEPARTMENT NAME
-- OUTPUT NUMBER OF STUDNET WHO IS PLAYING ANY SPORT IN THAT DEPARTMENT 

-- SOPRT PLAYING STUDNET 
CREATE PROCEDURE GET_STUDNET_DEPARTMETN_SPORT_DATA
@DEPT_NAME VARCHAR(100) 
AS 
BEGIN 

DECLARE @ORGINAL_DEPT_ID INT;
SELECT @ORGINAL_DEPT_ID= D.DEPARTMENT_ID FROM DEPARTMENT D WHERE D.DEPARTEMENT_NAME=@DEPT_NAME
SELECT * FROM STUDENT_INFORMATION SI
INNER JOIN STUDENT_SPORT_INFORMATION SSI 
ON SI.STUDENT_ID=SSI.STUDENT_ID
WHERE SI.DEPARTMENT_ID=@ORGINAL_DEPT_ID
END

GET_STUDNET_DEPARTMETN_SPORT_DATA @DEPT_NAME='Civil Departement'



-- QUE 3 : SPORT NAME GIVNG
-- OUTPUT: DEPARTMENT WISE COUNT OF STUDNET WHO IS PLAYING THAT SPORTS

