--DECLARING AND INITIALISING VARIBLES IN SQL SERVER

-- varible data type variable_name;

int a;
a=10;

int b=10;
--SYNTAX: DECLARE @VARIBLE_NAME DATA TYPE

DECLARE @VARIABLE_1 VARCHAR(100);

-- SET KEYWORD IS USED TO ASSIGN VALUE TO VARIBLE

SET @VARIABLE_1='TECHNORBIT';
SELECT  @VARIABLE_1='TECHNORBIT';


DECLARE @VARAIBLE_2 VARCHAR(100) ='TEST';


DECLARE @VARIABLE_3 VARCHAR(100);
DECLARE @VARIABLE_4 VARCHAR(100);
DECLARE @VARIABLE_5 VARCHAR(100);

DECLARE @VARIABLE_3 VARCHAR(100), @VARIABLE_5 VARCHAR(100) , @VARIABLE_4 INT;

SELECT @VARIABLE_3='ABC', @VARIABLE_5'XYZ', @VARIABLE_4 5



DECLARE @PPA_14 VARCHAR(100);
SET @PPA_14='TECHNORBIT';
PRINT @PPA_14 


SELECT * FROM EMPLOYEE E

--QUE: STORE ROLE OF RAVI KUMAR IN VARIBLE 

SELECT @ROLE_VARIABLE='ABC'



DECLARE @ROLE_VARIABLE VARCHAR(100);

SELECT @ROLE_VARIABLE=E.ROLE FROM EMPLOYEE E WHERE E.EMPLOYEEID=1
PRINT @ROLE_VARIABLE


SELECT * FROM STUDENT_INFORMATION SI
SELECT * FROM STUDENT_ACADAMIC_INFO

DECLARE @FE_SGPA_AVG DECIMAL(18,2)
SELECT @FE_SGPA_AVG=AVG(SAI.FE_CGPA) FROM  STUDENT_ACADAMIC_INFO SAI




DECLARE @PRITI_PERCENTAGE DECIMAL(18,2);
SELECT @PRITI_PERCENTAGE= PERCENTAGE FROM STUDENT_PERCENTAGE SP WHERE SP.ID=3
PRINT @PRITI_PERCENTAGE

IF @PRITI_PERCENTAGE>90
BEGIN 
PRINT 'EXCELLENT STUDENT '
END
ELSE IF @PRITI_PERCENTAGE > 80 AND @PRITI_PERCENTAGE<= 90
BEGIN
PRINT 'GOOD STUDNE '
END
ELSE IF @PRITI_PERCENTAGE BETWEEN 70 AND 80
BEGIN
PRINT 'AVG STUDNET'
END
ELSE 
BEGIN 
PRINT 'DULL STUDNET'
END 